"""Render an index ``README.md`` for the ADR directory."""

from __future__ import annotations

from typing import Iterable

from .parser import Adr


_HEADER = (
    "# Architecture Decision Records\n\n"
    "This directory contains the Architecture Decision Records (ADRs) for\n"
    "this project. ADRs document architecturally significant decisions and\n"
    "the context behind them.\n\n"
    "Each ADR is an immutable record. To change a decision, write a new ADR\n"
    "and supersede the old one.\n\n"
    "Generated by [adr-toolkit](https://github.com/intruderfr/adr-toolkit) —\n"
    "do not edit by hand; run `adr index` to refresh.\n\n"
)


def render_index(adrs: Iterable[Adr]) -> str:
    adrs = list(adrs)
    out = [_HEADER, "| #    | Status     | Title | Notes |\n",
           "|------|------------|-------|-------|\n"]

    if not adrs:
        out.append("| _no ADRs yet — run `adr new \"<title>\"`_ |  |  |  |\n")
        return "".join(out)

    for adr in adrs:
        notes = ""
        if adr.superseded_by is not None:
            notes = f"superseded by [{adr.superseded_by:04d}]" \
                    f"(./{_link_for(adrs, adr.superseded_by)})"
        elif adr.supersedes:
            joined = ", ".join(
                f"[{n:04d}](./{_link_for(adrs, n)})" for n in adr.supersedes
            )
            notes = f"supersedes {joined}"
        link = f"[{adr.title}](./{adr.path.name})"
        out.append(
            f"| {adr.number_str} | {adr.status:<10} | {link} | {notes} |\n"
        )
    return "".join(out)


def _link_for(adrs: Iterable[Adr], number: int) -> str:
    for a in adrs:
        if a.number == number:
            return a.path.name
    return f"{number:04d}-not-found.md"
